POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "hey",
  "important": true
}

###
GET http://localhost:3001/api/persons

### 
GET http://localhost:3001/info

###
GET http://localhost:3001/inf

###
GET http://localhost:3001/api/persons/6357e17030f3031c7bfd433d

###
GET http://localhost:3001/api/persons/5

### 
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "oasis",
  "number": 1234567
}

### 
PUT http://localhost:3001/api/persons/6359fb8c10308ee5cfd9dbcc
Content-Type: application/json

{
  "name": "oasis",
  "number": 777777
}

### 
PUT http://localhost:3001/api/persons/6359fb8c10308ee5cfd9dbcc
Content-Type: application/json

{
  "name": "sum 43",
  "number": 777777
}
