### 
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "secret"
}

###
GET http://localhost:3003/api/blog

###
POST http://localhost:3003/api/blog 
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNmU2ZjU2NTBmMzExYzc5YzBjZWRhMCIsImlhdCI6MTY2ODI3MTM0M30.P81TQAkkBNeOF0GDTlYgj3jyKaPPCc28MqAg6cPpIyc

{
  "title": "Dan Abramov6",
  "author": "Dan Abramov6",
  "url": "https://test6.com",
  "likes": 0,
  "userId": "636e6f5650f311c79c0ceda0"
}

###
POST http://localhost:3003/api/blog 
Content-Type: application/json

{
  "title": "Dan Abramov",
  "author": "Dan Abramov",
  "url": "https://test.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blog 
Content-Type: application/json

{
  "title": "Dan Abramov",
  "author": "Dan Abramov",
  "likes": 0
}

###
PUT http://localhost:3003/api/blog/6360015651fb32096906f9cf
Content-Type: application/json

{
  "likes": 25
}

### 
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "ro",
  "username": "roooo",
  "password": "se"
}
