###
GET http://localhost:3003/api/blog

###
POST http://localhost:3003/api/blog 
Content-Type: application/json

{
  "title": "Dan Abramov",
  "author": "Dan Abramov",
  "url": "https://test.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blog 
Content-Type: application/json

{
  "title": "Dan Abramov",
  "author": "Dan Abramov",
  "url": "https://test.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blog 
Content-Type: application/json

{
  "title": "Dan Abramov",
  "author": "Dan Abramov",
  "likes": 0
}